### ISSUE TITLE
TraitBank records are not subgrouped by statistical method, but are summarized under one random stat meth in the Data Tab

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#165]
Example: http://eol.org/pages/2540310/data#data_point_8477240

"water temperature (min)" heads up a list of two records, the second of which is a max.

**Comment by YoustinaAtef** [comment]
Fixed and pushed to master

**Comment by jhammock** [comment]
Post-deploy, it looks like this is still a problem. Could someone have another look?

**Comment by JRice** [comment]
Since I think Youstina is out, I'm taking this one.

**Comment by JRice** [comment]
Fixed.

**Comment by JRice** [comment]
Ooops deployed
